# Scorbit SDK
#
# (c) 2025 Spinner Systems, Inc. (DBA Scorbit), scorbit.io, All Rights Reserved
#
# MIT License
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

from __future__ import absolute_import

import os
from setuptools import setup, find_packages

here = os.path.abspath(os.path.dirname(__file__))

# _version.py is generated by scripts/python27-build.sh during wheel builds.
version_ns = {}
with open(os.path.join(here, "src", "scorbit", "_version.py")) as f:
    exec(f.read(), version_ns)

with open(os.path.join(here, "README.md")) as f:
    long_description = f.read()

setup(
    name="scorbit-py2",
    version=version_ns["__version__"],
    description="Python 2.7 wrapper for the Scorbit SDK (pinball scoring platform)",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Dilshod Mukhtarov",
    author_email="dilshodm@scorbit.io",
    url="https://scorbit.io",
    project_urls={
        "Repository": "https://github.com/scorbit-io/scorbit_sdk",
    },
    license="MIT",
    python_requires=">=2.7,<3",
    install_requires=["enum34"],
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    classifiers=[
        "Development Status :: 4 - Beta",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 2.7",
        "Operating System :: POSIX :: Linux",
        "Operating System :: MacOS",
        "Operating System :: Microsoft :: Windows",
        "Topic :: Games/Entertainment",
    ],
)
