set(sources
    source/test_main.cpp
    source/test_crypto_helpers.cpp
    source/test_crypto_utils.cpp
    source/test_libusb_cdc.cpp
    source/test_softwaretpm.cpp
    source/test_probetpm.cpp
    source/test_tpm_locate.cpp
)
