#!/bin/bash

# Scorbit SDK
#
# (c) 2025 Spinner Systems, Inc. (DBA Scorbit), scrobit.io, All Rights Reserved
#
# MIT License
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Build the scorbit wheel from a clean copy under build/build_python/stage/ so that:
# - Repo root VERSION is the only version source (no wrappers/python/VERSION file).
# - setuptools/pip never write a "build/" tree under wrappers/python/.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

source "$SCRIPT_DIR/_common.sh"
VER_STR=$(get_version "$REPO_ROOT/VERSION")

DIST_DIR="$REPO_ROOT/build/dist/$VER_STR"
WRAPPER_DIR="$REPO_ROOT/wrappers/python"
STAGE_ROOT="$REPO_ROOT/build/build_python"
STAGE="$STAGE_ROOT/stage"

mkdir -p "$DIST_DIR"

echo "!!! Building pure-Python wheel (scorbit $VER_STR) !!!"

# --- fresh stage (same idea as build/build_armhf*, but for Python packaging) ---
rm -rf "$STAGE"
mkdir -p "$STAGE"
cp -a "$WRAPPER_DIR/." "$STAGE/"
rm -rf "$STAGE/build" "$STAGE/.eggs" 2>/dev/null || true
find "$STAGE" -type d -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true
find "$STAGE" -type d -name '*.egg-info' -exec rm -rf {} + 2>/dev/null || true

# --- inject version from repo root (setuptools dynamic attr reads scorbit._version) ---
cat > "$STAGE/src/scorbit/_version.py" <<EOF
# Scorbit SDK
#
# (c) 2025 Spinner Systems, Inc. (DBA Scorbit), scorbit.io, All Rights Reserved
#
# MIT License
#
# Generated by scripts/python-build.sh from repo root VERSION — do not edit.

__version__ = "${VER_STR}"
EOF

# Python 3.6+ with pip. Python 2.7 cannot build this project.
_pick_wheel_python() {
    local candidates=()
    if [[ -n "${PYTHON:-}" ]]; then
        candidates+=("$PYTHON")
    fi
    candidates+=(python3 python)

    local py
    for py in "${candidates[@]}"; do
        command -v "$py" >/dev/null 2>&1 || continue
        if ! "$py" -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 6) else 1)" 2>/dev/null; then
            continue
        fi
        if "$py" -m pip --version >/dev/null 2>&1; then
            echo "$py"
            return 0
        fi
    done
    return 1
}

if ! PYTHON="$(_pick_wheel_python)"; then
    echo "Could not find Python 3.6+ with pip (python -m pip --version must work)."
    exit 1
fi

echo "Using: $($PYTHON -c "import sys; print(sys.executable)")"
echo "Staging directory: $STAGE"

# Debian/Ubuntu Docker images often ship pip 22.x that runs PEP 517 in-process hooks
# against the *system* setuptools (e.g. 59.x), which ignores PEP 621 [project] and
# produces UNKNOWN-0.0.0 wheels. Use pip >=24 so wheel builds use a proper isolated toolchain.
if ! "$PYTHON" -c "import sys
import pip
parts = pip.__version__.split(\".\")
maj = int(parts[0])
minr = int(parts[1]) if len(parts) > 1 else 0
sys.exit(0 if maj > 24 or (maj == 24 and minr >= 0) else 1)" 2>/dev/null; then
    echo "Upgrading pip (need >=24 for correct PEP 621 / pyproject wheel builds)..."
    "$PYTHON" -m pip install -q --upgrade "pip>=24.2"
fi

$PYTHON -m pip wheel "$STAGE" --no-deps -w "$DIST_DIR"

# Drop the staging tree unless debugging layout.
if [[ -z "${KEEP_PYTHON_BUILD_STAGE:-}" ]]; then
    rm -rf "$STAGE"
fi

# Remove legacy setuptools output under the source tree (older runs before staging).
rm -rf "$WRAPPER_DIR/build" 2>/dev/null || true
find "$WRAPPER_DIR" -maxdepth 2 -type d -name '*.egg-info' -exec rm -rf {} + 2>/dev/null || true

echo "Wheel created in $DIST_DIR"
