#!/bin/bash

# Scorbit SDK
#
# (c) 2025 Spinner Systems, Inc. (DBA Scorbit), scorbit.io, All Rights Reserved
#
# MIT License
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Build the scorbit (Python 2.7) wheel from a clean copy under
# build/build_python27/stage/ so that:
# - Repo root VERSION is the only version source (no wrappers/python27/VERSION file).
# - setuptools/pip never write a "build/" tree under wrappers/python27/.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

source "$SCRIPT_DIR/_common.sh"
VER_STR=$(get_version "$REPO_ROOT/VERSION")

# Same gcc-builder image as scripts/l-build.sh (see DOCKER_RELEASE).
if [[ ! -f /.dockerenv ]] && [[ -z "${SCORBIT_PYTHON_NO_DOCKER:-}" ]] && docker info >/dev/null 2>&1; then
    REL="$(cat "$REPO_ROOT/DOCKER_RELEASE")"
    REL="${REL//[$'\t\r\n ']}"
    BUILD_DIR="$REPO_ROOT/build/build_python27"
    DOCKER_IMAGE="dilshodm/gcc-builder:${REL}"
    echo "!!! Building pure-Python 2.7 wheel (scorbit $VER_STR) via Docker: $DOCKER_IMAGE !!!"
    docker_build_wheel "./scripts/python27-build.sh" "$DOCKER_IMAGE"
    exit 0
fi

DIST_DIR="$REPO_ROOT/build/dist/$VER_STR"
WRAPPER_DIR="$REPO_ROOT/wrappers/python27"
STAGE_ROOT="$REPO_ROOT/build/build_python27"
STAGE="$STAGE_ROOT/stage"

mkdir -p "$DIST_DIR"

echo "!!! Building pure-Python 2.7 wheel (scorbit $VER_STR) !!!"

# --- fresh stage (same idea as build/build_python, but for Python 2.7 packaging) ---
rm -rf "$STAGE"
mkdir -p "$STAGE"
cp -a "$WRAPPER_DIR/." "$STAGE/"
rm -rf "$STAGE/build" "$STAGE/.eggs" 2>/dev/null || true
find "$STAGE" -type d -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true
find "$STAGE" -type d -name '*.egg-info' -exec rm -rf {} + 2>/dev/null || true

# --- inject version from repo root ---
cat > "$STAGE/src/scorbit/_version.py" <<EOF
# Scorbit SDK
#
# (c) 2025 Spinner Systems, Inc. (DBA Scorbit), scorbit.io, All Rights Reserved
#
# MIT License
#
# Generated by scripts/python27-build.sh from repo root VERSION — do not edit.

__version__ = "${VER_STR}"
EOF

# Python 2.7 with pip.
_pick_wheel_python() {
    local candidates=()
    if [[ -n "${PYTHON:-}" ]]; then
        candidates+=("$PYTHON")
    fi
    candidates+=(python2.7 python2 python)

    local py
    for py in "${candidates[@]}"; do
        command -v "$py" >/dev/null 2>&1 || continue
        if ! "$py" -c "import sys; raise SystemExit(0 if sys.version_info[:2] == (2, 7) else 1)" 2>/dev/null; then
            continue
        fi
        if "$py" -m pip --version >/dev/null 2>&1; then
            echo "$py"
            return 0
        fi
    done
    return 1
}

if ! PYTHON="$(_pick_wheel_python)"; then
    echo "Could not find Python 2.7 with pip (python2.7 -m pip --version must work)."
    exit 1
fi

echo "Using: $($PYTHON -c "import sys; print(sys.executable)")"
echo "Staging directory: $STAGE"

$PYTHON -m pip wheel "$STAGE" --no-deps -w "$DIST_DIR"

# Drop the staging tree unless debugging layout.
if [[ -z "${KEEP_PYTHON_BUILD_STAGE:-}" ]]; then
    rm -rf "$STAGE"
fi

# Remove legacy setuptools output under the source tree (older runs before staging).
rm -rf "$WRAPPER_DIR/build" 2>/dev/null || true
find "$WRAPPER_DIR" -maxdepth 2 -type d -name '*.egg-info' -exec rm -rf {} + 2>/dev/null || true

echo "Wheel created in $DIST_DIR"
